# Generated by Django 4.2 on 2023-04-23 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cards", "0002_cardset_importance"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cardset",
            name="importance",
            field=models.BooleanField(default=False, null=True),
        ),
    ]
